### ISSUE TITLE
It's Same As v4

### ISSUE THREAD

**Issue by motiurrahaman** [tks18/gindex-v4-no-backend#3]
**First of all I wanna thank u for your best Gdrive Index**
Bro it's gindex-v4-no-backend but why does it need backened server. We want the easiest way create Gdrive Index. Also provide a tutorial video...**Please bro don't be offend**

**Comment by tks18** [comment]
I am lazy to update the readme bro
Nothing complicated to setup here.
Just see my worker file for setup

**Comment by motiurrahaman** [comment]
Thanks bro
